services:
  - type: web
    name: kdentrix-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
